"""RFC 5389 constants used by the STUN server.

STUN messages are binary records with a fixed 20 byte header followed by
32-bit padded attributes. This module intentionally contains only constants so
the protocol details stay explicit and easy to audit.
"""

from __future__ import annotations

MAGIC_COOKIE = 0x2112A442
HEADER_LENGTH = 20
TRANSACTION_ID_LENGTH = 12
ATTRIBUTE_HEADER_LENGTH = 4
ATTRIBUTE_ALIGNMENT = 4
MAX_STUN_DATAGRAM_SIZE = 548

BINDING_REQUEST = 0x0001
BINDING_RESPONSE = 0x0101
BINDING_ERROR_RESPONSE = 0x0111

ATTR_MAPPED_ADDRESS = 0x0001
ATTR_USERNAME = 0x0006
ATTR_MESSAGE_INTEGRITY = 0x0008
ATTR_ERROR_CODE = 0x0009
ATTR_UNKNOWN_ATTRIBUTES = 0x000A
ATTR_REALM = 0x0014
ATTR_NONCE = 0x0015
ATTR_XOR_MAPPED_ADDRESS = 0x0020
ATTR_SOFTWARE = 0x8022
ATTR_ALTERNATE_SERVER = 0x8023
ATTR_FINGERPRINT = 0x8028

FINGERPRINT_XOR = 0x5354554E
MESSAGE_INTEGRITY_LENGTH = 20
FINGERPRINT_LENGTH = 4

METHOD_BINDING = 0x001
CLASS_REQUEST = 0b00
CLASS_INDICATION = 0b01
CLASS_SUCCESS_RESPONSE = 0b10
CLASS_ERROR_RESPONSE = 0b11

REQUEST_CLASS = "request"
SUCCESS_RESPONSE_CLASS = "success_response"
ERROR_RESPONSE_CLASS = "error_response"
INDICATION_CLASS = "indication"

DEFAULT_CONFIG_PATHS = (
    "/etc/stun-server/config.toml",
    "./config.toml",
)
